'-----------------------------------------------------------'

'-----Provider----------------'
create table public.provider (
  provider_id integer generated always as identity not null,
  provider_name character varying(30) not null,
  provider_address character varying(35) not null,
  provider_city character varying(20) not null,
  provider_state character varying(15) not null,
  created_at timestamp with time zone null default now(),
  created_by text null default system_user,
  constraint provider_pkey primary key (provider_id),
  constraint provider_provider_name_key unique (provider_name)
) TABLESPACE pg_default;

'-----Patient----------------'
create table public.patient (
  patient_id integer generated by default as identity not null,
  provider_id integer not null,
  patient_first_name character varying(15) not null,
  patient_last_name character varying(15) not null,
  dob date not null,
  patient_address character varying(35) not null,
  patient_city character varying(20) not null,
  patient_state character varying(15) not null,
  patient_email character varying(25) null,
  patient_phone character varying(10) null,
  insurance_policy character varying(25) null,
  created_at timestamp with time zone null default now(),
  created_by text null default system_user,  
  constraint patient_pkey primary key (patient_id),
  constraint patient_provider_patient_identity_key unique (
    provider_id,
    patient_first_name,
    patient_last_name,
    dob
  )
) TABLESPACE pg_default;

'-----Invoices----------------'
create table public.invoices (
  invoice_id integer generated by default as identity not null,
  invoice_number character varying(50) not null,
  patient_id integer not null,
  invoice_date date not null,
  invoice_payment_date date not null,
  invoice_total numeric(9, 2) not null,
  payment_total numeric(9, 2) not null,
  insurance_adjustment numeric(9, 2) null,
  amount_due numeric(9, 2) null,
  created_at timestamp with time zone null default now(),
  created_by text null default system_user,  
  constraint invoices_pkey primary key (invoice_id),
  constraint invoices_invoice_number_key unique (invoice_number)
) TABLESPACE pg_default;

'-----Invoice_Items----------------'
create table public.invoice_items (
  invoice_id integer not null,
  line_item_code character varying(10) not null,
  line_item_description character varying(100) not null,
  line_item_amount numeric(9, 2) not null,
  line_item_quantity integer not null,
  created_at timestamp with time zone null default now(),
  created_by text null default system_user,  
  constraint invoice_items_pkey primary key (invoice_id, line_item_code),
  constraint invoice_items_invoice_line_code_key unique (invoice_id, line_item_code),
  constraint invoice_line_items_fk_invoices foreign KEY (invoice_id) references invoices (invoice_id)
) TABLESPACE pg_default;

'-----Invoice_Batch----------------'
create table public.invoice_batch (
  client_batch_id uuid not null,
  invoice_ord integer not null,
  invoice_id integer not null,
  created_at timestamp with time zone not null default now(),
  created_by text null default system_user,  
  constraint invoice_batch_client_batch_id_invoice_ord_key unique (client_batch_id, invoice_ord)
) TABLESPACE pg_default;

create unique INDEX IF not exists invoice_batch_uniq_ord on public.invoice_batch using btree (client_batch_id, invoice_ord) TABLESPACE pg_default;

create unique INDEX IF not exists invoice_batch_uniq_invoice on public.invoice_batch using btree (client_batch_id, invoice_id) TABLESPACE pg_default;

'-----Invoice_Reviews----------------'
create table public.invoice_reviews (
  id uuid not null default gen_random_uuid (),
  image_path text null,
  raw_ocr_text text null,
  extracted_json jsonb null,
  failure_reasons text[] null,
  status text null default 'pending'::text,
  reviewer_comment text null,
  reviewed_at timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  constraint invoice_reviews_pkey primary key (id)
) TABLESPACE pg_default;